// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class partial_required_productid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partial_required_productid));
        
        string IMigrationMetadata.Id
        {
            get { return "201511200340032_partial_required_productid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
