// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shippingmethod_requiredcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shippingmethod_requiredcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201507091515292_shippingmethod_requiredcategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
