// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product_taxable_taxprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_taxable_taxprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "201509152351145_product_taxable_taxprofile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
