// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orderproduct_salvageprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderproduct_salvageprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "201508131201067_orderproduct_salvageprofile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
