// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RMANumberCreatedOn_ExpirationDays_AddedIn_Order_RMAReason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RMANumberCreatedOn_ExpirationDays_AddedIn_Order_RMAReason));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041920457_RMANumberCreatedOn_ExpirationDays_AddedIn_Order_RMAReason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
