// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Weight_ValueType_Changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Weight_ValueType_Changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151659219_Weight_ValueType_Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
