// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Order_Remove_LastChildId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_Remove_LastChildId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611261256482_Order_Remove_LastChildId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
