// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForgotPassword_190 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForgotPassword_190));
        
        string IMigrationMetadata.Id
        {
            get { return "201607031845549_ForgotPassword_190"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
