// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NextSalvageProfileId_in_OP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NextSalvageProfileId_in_OP));
        
        string IMigrationMetadata.Id
        {
            get { return "201611272359549_NextSalvageProfileId_in_OP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
