// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PorcessorSpecificText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PorcessorSpecificText));
        
        string IMigrationMetadata.Id
        {
            get { return "201606172001346_PorcessorSpecificText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
