// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PartialDate_In_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PartialDate_In_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "201609171358401_PartialDate_In_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
