// <auto-generated />
namespace KontinuityCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsentcolumn_in_triggerEmailTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsentcolumn_in_triggerEmailTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201610261306210_addsentcolumn_in_triggerEmailTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
